#!/sbin/sh

# event is device specific
case `getprop ro.product.device` in
anzu)
    cat /dev/input/event1 > /dev/keycheck& >/dev/null 2>&1
;;
hallon)
    cat /dev/input/event1 > /dev/keycheck& >/dev/null 2>&1
;;
mango)
    cat /dev/input/event2 > /dev/keycheck& >/dev/null 2>&1
;;
smultron)
    cat /dev/input/event2 > /dev/keycheck& >/dev/null 2>&1
;;
urushi)
    cat /dev/input/event2 > /dev/keycheck& >/dev/null 2>&1
;;
zeus)
    cat /dev/input/event2 > /dev/keycheck& >/dev/null 2>&1
;;
esac

sleep 3
kill -9 $!
if [ -s /dev/keycheck -o -e /cache/recovery/boot ]
then
# fixing CPU clocks to avoid issues in recovery
echo 1024000 > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq
echo 245000 > /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq

rm /cache/recovery/boot
mount -o remount,rw rootfs /
umount -l /system
umount -l /data
umount -l /cache
umount -l /mnt/sdcard
rm -r /sdcard
rm -r /not/sdcard
mkdir /sdcard
mkdir /tmp
rm /etc
mkdir /etc
cp /recovery.fstab /etc/recovery.fstab
mount /dev/block/mmcblk0p1 /sdcard
/sbin/recovery &
/sbin/adbd recovery 
fi

#continue booting

