#!/bin/busybox sh
export _PATH="$PATH"
export PATH=/bin

busybox cd /
busybox date >> boot.txt
exec >> boot.txt 2>&1
busybox rm init

busybox mkdir /proc/
busybox mkdir /sys/
busybox mkdir /dev/
busybox mkdir /dev/block/
busybox mkdir /system/
busybox mkdir /cache/

busybox mknod /dev/null c 1 3
busybox mknod /dev/block/mtdblock0 b 31 0
busybox mknod /dev/block/mtdblock0 b 31 0
busybox mknod /dev/block/mtdblock1 b 31 1
busybox mknod /dev/block/mtdblock2 b 31 2
busybox mknod /dev/block/mtdblock3 b 31 3

busybox mount -t proc proc /proc
busybox mount -t sysfs sysfs /sys

busybox mount -t yaffs2 /dev/block/mtdblock0 /system
busybox mount -t yaffs2 /dev/block/mtdblock2 /cache

BOOT_RAMDISK=/stage2/boot.cpio
if busybox test -e /cache/recovery/boot || busybox grep -q startup=0x00000020 /proc/cmdline; then
	busybox rm -rf /cache/recovery/boot
	BOOT_RAMDISK=/stage2/recovery.cpio
fi

busybox umount /cache
busybox umount /system

busybox rmdir /cache
busybox rmdir /system

busybox zcat $BOOT_RAMDISK | busybox cpio -i
busybox umount /sys
busybox umount /proc
busybox date >> boot.txt
busybox rm -rf /stage2 /bin /dev/*

export PATH="${_PATH}"
exec /init
